CompUnit {
    items: [
        FuncDef(
            NormalFunc(
                i32,
                Ident {
                    ident: "main",
                },
                [],
                NormalBlock(
                    [
                        Stmt(
                            MatchedStmt(
                                MatchedStmt {
                                    NormalMatchedStmt: ReturnStmt(
                                        Some(
                                            LogicOrExpr(
                                                LogicAndExpr(
                                                    EqExpr(
                                                        RelExpr(
                                                            AddExpr(
                                                                MulExpr(
                                                                    UnaryExpr(
                                                                        PrimaryExpr(
                                                                            Literal(
                                                                                IntConst(
                                                                                    0,
                                                                                ),
                                                                            ),
                                                                        ),
                                                                    ),
                                                                ),
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                },
                            ),
                        ),
                    ],
                ),
            ),
        ),
    ],
}